### ISSUE TITLE
Audit log feature is required in the Omni Panel

### ISSUE THREAD

**Issue by harshalpatel-inventyv** [siderolabs/omni-feedback#68] opened 2023-11-21 07:45 UTC
### Problem Description

Hello,

We've multiple users accounts for Omni Panel and currently, Omni does not provide an audit log so due to this we're not able to track who makes changes in config patches or other cluster-level changes so we need an audit logs feature in the Omni panel, whenever any user makes changes in config patches or does cluster-related changes at that time logs should be generated & preserved somewhere.

### Solution

We want an audit logs feature in the omni panel, whenever any user makes changes in config patches or does cluster-related changes at that time logs should be generated & preserved somewhere.

It is must needed feature in Omni where multiple users have access to the Omni panel.

Let us know when can we expect this feature.

**Comment by steverfrancis** [comment] 2024-04-05 23:27
Duplicate of https://github.com/siderolabs/omni/issues/37

**Closed as completed** 2024-04-05 23:30 UTC
