### ISSUE TITLE
[bug] new machine not visible in Omni

### ISSUE THREAD

**Issue by Dids** [siderolabs/omni-feedback#78] opened 2024-02-23 11:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Booting a bare metal server with an Omni-generated disk image should show up under `Machines` in the Omni website, and while it previously did, after I deleted it and reinstalled the same bare metal server multiple times in a row, it is no longer appearing in the web interfaces, ~~and for some strange reason the web interface shows that my machine limit is now 4 instead of 6~~.

I'm assuming there's some kind of inconsistency/bug here where the existing server is still considered "discovered" but is not being shown due to being deleted before.

### Expected Behavior

I expected to see the machine show up in Omni, especially since it responds to ping and I can sort of connect to it with `talosctl`, however it does error out with "cluster name not set", which I'm also assuming would be normal in this case.
Additionally, I'm expecting to see 6 available machine/node slots instead of the 4 that it's showing now.

### Steps To Reproduce

1. Create a bare-metal machine image in Omni and download it (version and extensions don't seem to matter)
2. Apply the disk image to a disk on the server
3. Verify that the server is back up (responds to ping is usually a good enough indicator in my experience)
4. Try adding the server to an existing cluster, but it keeps failing due to somewhat unrelated issues
5. Delete the server from the cluster/from Omni
6. Keep trying again, until it no longer appears in Omni at all

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge

### Anything else?

Account name is `didstopia`, in case you can check for account related issues etc.

**Comment by rsmitty** [comment] 2024-02-23 16:06
Did you delete the machine from omni (not from the cluster, but from the Machines view)? If so, you'll need to wipe the disk completely before it will rejoin.

**Comment by Dids** [comment] 2024-02-24 07:35
> Did you delete the machine from omni (not from the cluster, but from the Machines view)? If so, you'll need to wipe the disk completely before it will rejoin.

Indeed I did. And as to the wiping, I've wiped it numerous times using different approaches, such as fdisk and gdisk, then reapplying the machine disk image.

The machine has two identical drives, which makes me all of this a bit more tedious, especially as the order of the drives is not guaranteed, so I've tried to keep one of them entirely empty (no partition table or anything) while only applying the disk image to the other disk.

I'm assuming that the UUID of the machine doesn't ever change, unless it's tied to the machine disk image (the machine disk image always assigns the same disk identifier for example), and at this point it feels like Omni is still thinking that it's the same machine that was previously deleted, which it is, but no amount of disk clearing or reapplying the disk image seems to bring it back to being visible, which is why it feels like a bug of some sort. Haven't had this happen before either, and I've gone through quite a few of these installs.

**Comment by Dids** [comment] 2024-02-25 13:17
Okay, this is _definitely_ a bug, at least from what I can gather.

1. Here's a screenshot of the`Machines` view, showing only 3 machines, all of which are control plane nodes that are part of an active cluster. Notice that there are no other machines visible.
![Näyttökuva 2024-2-25 kello 15 12 45](https://github.com/siderolabs/omni-feedback/assets/3455449/13264236-bafe-4c5c-aa98-e2204caa3315)

2. Now if I go to `Machine Classes` view, I suddenly see the machine that I was expecting to see. Also notice that it shows `available` and `disconnected`.
![Näyttökuva 2024-2-25 kello 15 11 24](https://github.com/siderolabs/omni-feedback/assets/3455449/01e33f0b-1f2c-448e-b66d-c16d5e737076)

3. Now when I click on the machine's name/UUID, I can suddenly see up-to-date logs from the machine, meaning that it's still streaming logs to Omni at the time of writing this, so it's definitely up and running, as well as connected to Omni.
![Näyttökuva 2024-2-25 kello 15 12 21](https://github.com/siderolabs/omni-feedback/assets/3455449/f6099c8c-bc73-4315-8553-4280e86a263f)

Unfortunately I can't do anything as it stands, since I can't actually see the machine under the `Machines` view. Reinstalling doesn't seem to do anything to change the situation, ~~and the fact that Omni is reporting that I have only `4` machine/node slots instead of the `6` included with my plan,~~ it does very much feel like a bug.

**Comment by Dids** [comment] 2024-02-25 14:08
Looks like this is the same issue as https://github.com/siderolabs/omni-feedback/issues/77.

Eg. using `omnictl get machines` I can definitely see the missing machine, but attempting to delete it via `omnictl` results in the following error:
```sh
> omnictl get machines
NAMESPACE   TYPE      ID                                     VERSION   ADDRESS                                   CONNECTED   REBOOTS
default     Machine   3820c67f-d211-41c6-b03d-5e351c4b99ed   10        fdae:41e4:649b:9303:d60c:e720:3ac1:a56f   true        
default     Machine   9600a118-0be2-4459-bdb6-968839d1b0d5   10        fdae:41e4:649b:9303:d303:4b49:22d5:43aa   true        
default     Machine   a9f141f0-fcdb-3adf-ff20-08bfb813d48f   11        fdae:41e4:649b:9303:dd01:f0ac:4277:eb00   true        
default     Machine   eca7e865-dad4-4c84-a114-d4890e7baa6c   10        fdae:41e4:649b:9303:9c32:b3e8:1238:5b6a   true

> omnictl delete machine a9f141f0-fcdb-3adf-ff20-08bfb813d48f
Error: rpc error: code = PermissionDenied desc = failed to validate: 1 error occurred:
        * rpc error: code = PermissionDenied desc = only read access is permitted
```

EDIT: Whoops, I realized I only tried with `delete machine` and not with `delete link`, which actually succeeded:
```sh
> omnictl delete link a9f141f0-fcdb-3adf-ff20-08bfb813d48f
torn down Links.omni.sidero.dev a9f141f0-fcdb-3adf-ff20-08bfb813d48f
destroyed Links.omni.sidero.dev a9f141f0-fcdb-3adf-ff20-08bfb813d48f
destroyed Links.omni.sidero.dev a9f141f0-fcdb-3adf-ff20-08bfb813d48f
```

UPDATE: That was it! I reapplied the disk image again afterwards, the machine showed up in Omni again and I successfully added it to the cluster. Confirmed to be the same issue as #77. Regarding the 4 machines instead of 6, I think that was just saying 4 because of the 3 control plane nodes + the missing machine, so it has nothing to do with the plan limits etc.

**Comment by steverfrancis** [comment] 2024-04-05 23:39
Duplicate of https://github.com/siderolabs/omni-feedback/issues/77

**Closed as completed by steverfrancis** 2024-04-05 23:39 UTC
Labels: bug
